=== gpitteloud/hisrc-basicjaxb/higher/tests/fixed-value/src/main/resources/document.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
	targetNamespace="http://example.org/document"
	xmlns:tns="http://example.org/document"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:jaxb="https://jakarta.ee/xml/ns/jaxb"
	jaxb:version="3.0"
>

	<!-- Anonymous simple type -->
	<xs:element name="fv_limit" fixed="1000">
		<xs:simpleType>
			<xs:restriction base="xs:int">
				<xs:minInclusive value="1" />
				<xs:maxInclusive value="10000" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:simpleType name="dowType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Sunday" />
			<xs:enumeration value="Monday" />
			<xs:enumeration value="Tuesday" />
			<xs:enumeration value="Wednesday" />
			<xs:enumeration value="Thursday" />
			<xs:enumeration value="Friday" />
			<xs:enumeration value="Saturday" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Common Primitive and Derived Datatypes -->
	
	<xs:element name="fv_dow"           type="tns:dowType"      fixed="Monday"/>
	<xs:element name="fv_boolean"       type="xs:boolean"       fixed="true"/>
	<xs:element name="fv_byte"          type="xs:byte"          fixed="-1"/>
	<xs:element name="fv_decimal"       type="xs:decimal"       fixed="-2.1"/>
	<xs:element name="fv_double"        type="xs:double"        fixed="-3.1"/>
	<xs:element name="fv_float"         type="xs:float"         fixed="-4.1"/>
	<xs:element name="fv_int"           type="xs:int"           fixed="-5"/>
	<xs:element name="fv_integer"       type="xs:integer"       fixed="-6"/>
	<xs:element name="fv_long"          type="xs:long"          fixed="-7"/>
	<xs:element name="fv_short"         type="xs:short"         fixed="-8"/>
	<xs:element name="fv_string"        type="xs:string"        fixed="text"/>
	<xs:element name="fv_dateTime"      type="xs:dateTime"      fixed="2023-02-28T17:59:59.999Z"/>
	<xs:element name="fv_duration"      type="xs:duration"      fixed="P3Y2M1D" />
	<xs:element name="fv_base64Binary"  type="xs:base64Binary"  fixed="dGV4dA==" />
	<xs:element name="fv_hexBinary"     type="xs:hexBinary"     fixed="0FB8" />
	<xs:element name="fv_anySimpleType" type="xs:anySimpleType" fixed="3.14159" />
	
	<xs:element name="fv_choice">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="tns:fv_boolean" />
				<xs:element ref="tns:fv_string" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="document1">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:fv_limit" />
				<xs:element ref="tns:fv_dow" />
				<xs:element ref="tns:fv_boolean" />
				<xs:element ref="tns:fv_byte" />
				<xs:element ref="tns:fv_choice" />
				<xs:element ref="tns:fv_decimal" />
				<xs:element ref="tns:fv_double" />
				<xs:element ref="tns:fv_float" />
				<xs:element ref="tns:fv_int" />
				<xs:element ref="tns:fv_integer" />
				<xs:element ref="tns:fv_long" />
				<xs:element ref="tns:fv_short" />
				<xs:element ref="tns:fv_string" />
				<xs:element ref="tns:fv_dateTime" />
				<xs:element ref="tns:fv_duration" />
				<xs:element ref="tns:fv_base64Binary" />
				<xs:element ref="tns:fv_hexBinary" />
				<xs:element ref="tns:fv_anySimpleType" />
			</xs:sequence>
			<xs:attribute name="fa_limit"                                 fixed="1000">
				<xs:annotation>
					<xs:appinfo>
						<jaxb:property>
							<jaxb:javadoc>FA LIMIT</jaxb:javadoc>
						</jaxb:property>
					</xs:appinfo>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="1" />
						<xs:maxInclusive value="10000" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="fa_dow"           type="tns:dowType"      fixed="Monday" />
			<xs:attribute name="fa_boolean"       type="xs:boolean"       fixed="true" />
			<xs:attribute name="fa_byte"          type="xs:byte"          fixed="+1" />
			<xs:attribute name="fa_decimal"       type="xs:decimal"       fixed="+2.1" />
			<xs:attribute name="fa_double"        type="xs:double"        fixed="+3.1" />
			<xs:attribute name="fa_float"         type="xs:float"         fixed="+4.1" />
			<xs:attribute name="fa_int"           type="xs:int"           fixed="+5" />
			<xs:attribute name="fa_integer"       type="xs:integer"       fixed="+6" />
			<xs:attribute name="fa_long"          type="xs:long"          fixed="+7" />
			<xs:attribute name="fa_short"         type="xs:short"         fixed="+8" />
			<xs:attribute name="fa_string"        type="xs:string"        fixed="text" />
			<xs:attribute name="fa_dateTime"      type="xs:dateTime"      fixed="2023-02-28T17:59:59.999Z" />
			<xs:attribute name="fa_duration"      type="xs:duration"      fixed="P3Y2M1D" />
			<xs:attribute name="fa_base64Binary"  type="xs:base64Binary"  fixed="dGV4dA==" />
			<xs:attribute name="fa_hexBinary"     type="xs:hexBinary"     fixed="0FB8" />
			<xs:attribute name="fa_anySimpleType" type="xs:anySimpleType" fixed="3.14159" />
		</xs:complexType>
	</xs:element>

	<!-- Primitive Datatypes -->
	
	<xs:element name="fv_time"          type="xs:time"          fixed="23:59:59" />
	<xs:element name="fv_date"          type="xs:date"          fixed="2023-02-28Z" />
	<xs:element name="fv_gYearMonth"    type="xs:gYearMonth"    fixed="2023-02Z" />
	<xs:element name="fv_gYear"         type="xs:gYear"         fixed="2023Z" />
	<xs:element name="fv_gMonthDay"     type="xs:gMonthDay"     fixed="--02-28Z" />
	<xs:element name="fv_gDay"          type="xs:gDay"          fixed="---28Z" />
	<xs:element name="fv_gMonth"        type="xs:gMonth"        fixed="--02Z" />
	<xs:element name="fv_anyURI"        type="xs:anyURI"        fixed="scheme://authority/path?query#fragment" />
	<xs:element name="fv_QName"         type="xs:QName"         fixed="tns:localPart" />
	
	<xs:element name="document2">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:fv_string" />
				<xs:element ref="tns:fv_boolean" />
				<xs:element ref="tns:fv_decimal" />
				<xs:element ref="tns:fv_float" />
				<xs:element ref="tns:fv_double" />
				<xs:element ref="tns:fv_duration" />
				<xs:element ref="tns:fv_dateTime" />
				<xs:element ref="tns:fv_time" />
				<xs:element ref="tns:fv_date" />
				<xs:element ref="tns:fv_gYearMonth" />
				<xs:element ref="tns:fv_gYear" />
				<xs:element ref="tns:fv_gMonthDay" />
				<xs:element ref="tns:fv_gDay" />
				<xs:element ref="tns:fv_gMonth" />
				<xs:element ref="tns:fv_hexBinary" />
				<xs:element ref="tns:fv_base64Binary" />
				<xs:element ref="tns:fv_anyURI" />
				<xs:element ref="tns:fv_QName" />
			</xs:sequence>
			<xs:attribute name="fa_string"        type="xs:string"        fixed="text" />
			<xs:attribute name="fa_boolean"       type="xs:boolean"       fixed="true" />
			<xs:attribute name="fa_decimal"       type="xs:decimal"       fixed="2.1" />
			<xs:attribute name="fa_float"         type="xs:float"         fixed="4.1" />
			<xs:attribute name="fa_double"        type="xs:double"        fixed="3.1" />
			<xs:attribute name="fa_duration"      type="xs:duration"      fixed="P3Y2M1D" />
			<xs:attribute name="fa_dateTime"      type="xs:dateTime"      fixed="2023-02-28T17:59:59.999Z" />
			<xs:attribute name="fa_time"          type="xs:time"          fixed="23:59:59"/>
			<xs:attribute name="fa_date"          type="xs:date"          fixed="2023-02-28Z"/>
			<xs:attribute name="fa_gYearMonth"    type="xs:gYearMonth"    fixed="2023-02Z"/>
			<xs:attribute name="fa_gYear"         type="xs:gYear"         fixed="2023Z"/>
			<xs:attribute name="fa_gMonthDay"     type="xs:gMonthDay"     fixed="--02-28Z"/>
			<xs:attribute name="fa_gDay"          type="xs:gDay"          fixed="---28Z"/>
			<xs:attribute name="fa_gMonth"        type="xs:gMonth"        fixed="--02Z"/>
			<xs:attribute name="fa_hexBinary"     type="xs:hexBinary"     fixed="0FB8" />
			<xs:attribute name="fa_base64Binary"  type="xs:base64Binary"  fixed="dGV4dA==" />
			<xs:attribute name="fa_anyURI"        type="xs:anyURI"        fixed="scheme://authority/path?query#fragment"/>
			<xs:attribute name="fa_QName"         type="xs:QName"         fixed="tns:localPart"/>
		</xs:complexType>
	</xs:element>

	<!-- Derived Datatypes -->

	<xs:element name="fv_normalizedString"   type="xs:normalizedString"   fixed="normal" />
	<xs:element name="fv_token"              type="xs:token"              fixed="token" />
	<xs:element name="fv_language"           type="xs:language"           fixed="en-US" />
	<xs:element name="fv_nmtoken"            type="xs:NMTOKEN"            fixed="nospace" />
	<xs:element name="fv_nmtokens"           type="xs:NMTOKENS"           fixed="nospace1 nospace2" />
	<xs:element name="fv_nonPositiveInteger" type="xs:nonPositiveInteger" fixed="0" />
	<xs:element name="fv_negativeInteger"    type="xs:negativeInteger"    fixed="-16" />
	<xs:element name="fv_nonNegativeInteger" type="xs:nonNegativeInteger" fixed="0" />
	<xs:element name="fv_unsignedLong"       type="xs:unsignedLong"       fixed="7" />
	<xs:element name="fv_unsignedInt"        type="xs:unsignedInt"        fixed="5" />
	<xs:element name="fv_unsignedShort"      type="xs:unsignedShort"      fixed="8" />
	<xs:element name="fv_unsignedByte"       type="xs:unsignedByte"       fixed="1" />
	<xs:element name="fv_positiveInteger"    type="xs:positiveInteger"    fixed="+16" />

	<xs:element name="document3">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:fv_normalizedString" />
				<xs:element ref="tns:fv_token" />
				<xs:element ref="tns:fv_language" />
				<xs:element ref="tns:fv_nmtoken" />
				<xs:element ref="tns:fv_nmtokens" />
				<xs:element ref="tns:fv_integer" />
				<xs:element ref="tns:fv_nonPositiveInteger" />
				<xs:element ref="tns:fv_negativeInteger" />
				<xs:element ref="tns:fv_long" />
				<xs:element ref="tns:fv_int" />
				<xs:element ref="tns:fv_short" />
				<xs:element ref="tns:fv_byte" />
				<xs:element ref="tns:fv_nonNegativeInteger" />
				<xs:element ref="tns:fv_unsignedLong" />
				<xs:element ref="tns:fv_unsignedInt" />
				<xs:element ref="tns:fv_unsignedShort" />
				<xs:element ref="tns:fv_unsignedByte" />
				<xs:element ref="tns:fv_positiveInteger" />
			</xs:sequence>
			<xs:attribute name="fa_normalizedString"   type="xs:normalizedString"   fixed="normal" />
			<xs:attribute name="fa_token"              type="xs:token"              fixed="token" />
			<xs:attribute name="fa_language"           type="xs:language"           fixed="en-US" />
			<xs:attribute name="fa_nmtoken"            type="xs:NMTOKEN"            fixed="nospace" />
			<xs:attribute name="fa_nmtokens"           type="xs:NMTOKENS"           fixed="nospace1 nospace2" />
			<xs:attribute name="fa_integer"            type="xs:integer"            fixed="-6" />
			<xs:attribute name="fa_nonPositiveInteger" type="xs:nonPositiveInteger" fixed="0" />
			<xs:attribute name="fa_negativeInteger"    type="xs:negativeInteger"    fixed="-16" />
			<xs:attribute name="fa_long"               type="xs:long"               fixed="-7" />
			<xs:attribute name="fa_int"                type="xs:int"                fixed="-5" />
			<xs:attribute name="fa_short"              type="xs:short"              fixed="-8" />
			<xs:attribute name="fa_byte"               type="xs:byte"               fixed="-1" />
			<xs:attribute name="fa_nonNegativeInteger" type="xs:nonNegativeInteger" fixed="0" />
			<xs:attribute name="fa_unsignedLong"       type="xs:unsignedLong"       fixed="7" />
			<xs:attribute name="fa_unsignedInt"        type="xs:unsignedInt"        fixed="5" />
			<xs:attribute name="fa_unsignedShort"      type="xs:unsignedShort"      fixed="8" />
			<xs:attribute name="fa_unsignedByte"       type="xs:unsignedByte"       fixed="1" />
			<xs:attribute name="fa_positiveInteger"    type="xs:positiveInteger"    fixed="+16" />
		</xs:complexType>
	</xs:element>

	<!-- List Datatypes -->

	<xs:simpleType name="decimalList">  <xs:list itemType="xs:decimal"/>  </xs:simpleType>
	<xs:simpleType name="integerList">  <xs:list itemType="xs:integer"/>  </xs:simpleType>
	<xs:simpleType name="booleanList">  <xs:list itemType="xs:boolean"/>  </xs:simpleType>
	<xs:simpleType name="byteList">     <xs:list itemType="xs:byte"/>     </xs:simpleType>
	<xs:simpleType name="doubleList">   <xs:list itemType="xs:double"/>   </xs:simpleType>
	<xs:simpleType name="durationList"> <xs:list itemType="xs:duration"/> </xs:simpleType>
	<xs:simpleType name="floatList">    <xs:list itemType="xs:float"/>    </xs:simpleType>
	<xs:simpleType name="intList">      <xs:list itemType="xs:int"/>      </xs:simpleType>
	<xs:simpleType name="longList">     <xs:list itemType="xs:long"/>     </xs:simpleType>
	<xs:simpleType name="shortList">    <xs:list itemType="xs:short"/>    </xs:simpleType>
	<xs:simpleType name="stringList">   <xs:list itemType="xs:string"/>   </xs:simpleType>
	<xs:simpleType name="dateTimeList"> <xs:list itemType="xs:dateTime"/> </xs:simpleType>

	<xs:element name="fv_decimalValues"  type="tns:decimalList"  fixed="-7.50 5.75"/>
	<xs:element name="fv_integerValues"  type="tns:integerList"  fixed="-11 13"/>
	<xs:element name="fv_booleanValues"  type="tns:booleanList"  fixed="true false"/>
	<xs:element name="fv_byteValues"     type="tns:byteList"     fixed="-128 127"/>
	<xs:element name="fv_doubleValues"   type="tns:doubleList"   fixed="-3.14 2.718 -INF INF NaN"/>
	<xs:element name="fv_durationValues" type="tns:durationList" fixed="P3Y2M1D P6Y4M2D"/>
	<xs:element name="fv_floatValues"    type="tns:floatList"    fixed="-3.14 2.718 -INF INF NaN"/>
	<xs:element name="fv_intValues"      type="tns:intList"      fixed="-123 123"/>
	<xs:element name="fv_longValues"     type="tns:longList"     fixed="-123 123"/>
	<xs:element name="fv_shortValues"    type="tns:shortList"    fixed="-123 123"/>
	<xs:element name="fv_stringValues"   type="tns:stringList"   fixed="string1 string2"/>
	<xs:element name="fv_dateTimeValues" type="tns:dateTimeList" fixed="2023-02-28T17:59:59.999Z 2023-03-01T17:59:59.999Z"/>
	
	<xs:element name="document4">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:fv_decimalValues" />
				<xs:element ref="tns:fv_integerValues" />
				<xs:element ref="tns:fv_booleanValues" />
				<xs:element ref="tns:fv_byteValues" />
				<xs:element ref="tns:fv_doubleValues" />
				<xs:element ref="tns:fv_durationValues" />
				<xs:element ref="tns:fv_floatValues" />
				<xs:element ref="tns:fv_intValues" />
				<xs:element ref="tns:fv_longValues" />
				<xs:element ref="tns:fv_shortValues" />
				<xs:element ref="tns:fv_stringValues" />
				<xs:element ref="tns:fv_dateTimeValues" />
			</xs:sequence>
			<xs:attribute name="fa_decimalValues"  type="tns:decimalList"  fixed="-7.50 5.75" />
			<xs:attribute name="fa_integerValues"  type="tns:integerList"  fixed="-11 13" />
			<xs:attribute name="fa_booleanValues"  type="tns:booleanList"  fixed="true false" />
			<xs:attribute name="fa_byteValues"     type="tns:byteList"     fixed="-128 127" />
			<xs:attribute name="fa_doubleValues"   type="tns:doubleList"   fixed="-3.14 2.718 -INF INF NaN" />
			<xs:attribute name="fa_durationValues" type="tns:durationList" fixed="P3Y2M1D P6Y4M2D" />
			<xs:attribute name="fa_floatValues"    type="tns:floatList"    fixed="-3.14 2.718 -INF INF NaN" />
			<xs:attribute name="fa_intValues"      type="tns:intList"      fixed="-123 123" />
			<xs:attribute name="fa_longValues"     type="tns:longList"     fixed="-123 123" />
			<xs:attribute name="fa_shortValues"    type="tns:shortList"    fixed="-123 123" />
			<xs:attribute name="fa_stringValues"   type="tns:stringList"   fixed="string1 string2" />
			<xs:attribute name="fa_dateTimeValues" type="tns:dateTimeList" fixed="2023-02-28T17:59:59.999Z 2023-03-01T17:59:59.999Z" />
		</xs:complexType>
	</xs:element>

</xs:schema>

=== gpitteloud/hisrc-basicjaxb/higher/tests/fixed-value/src/test/samples/document3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
3.3 Derived datatypes
	3.3.1 normalizedString
	3.3.2 token
	3.3.3 language
	3.3.4 NMTOKEN
	3.3.5 NMTOKENS
	3.3.6 Name
	3.3.7 NCName
	3.3.8 ID
	3.3.9 IDREF
	3.3.10 IDREFS
	3.3.11 ENTITY
	3.3.12 ENTITIES
	3.3.13 integer
	3.3.14 nonPositiveInteger
	3.3.15 negativeInteger
	3.3.16 long
	3.3.17 int
	3.3.18 short
	3.3.19 byte
	3.3.20 nonNegativeInteger
	3.3.21 unsignedLong
	3.3.22 unsignedInt
	3.3.23 unsignedShort
	3.3.24 unsignedByte
	3.3.25 positiveInteger
-->
<ns3:document3
	xmlns:ns3="http://example.org/document" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://example.org/document ../../main/resources/document.xsd "
	
	fa_normalizedString="normal"
	fa_token="token"
	fa_language="en-US"
	fa_nmtoken="nospace"
	fa_integer="-6"
	fa_nonPositiveInteger="0"
	fa_negativeInteger="-16"
	fa_long="-7"
	fa_int="-5"
	fa_short="-8"
	fa_byte="-1"
	fa_nonNegativeInteger="0"
	fa_unsignedLong="7"
	fa_unsignedInt="5"
	fa_unsignedShort="8"
	fa_unsignedByte="1"
	fa_positiveInteger="+16"
>
	<ns3:fv_normalizedString>normal</ns3:fv_normalizedString>
	<ns3:fv_token>token</ns3:fv_token>
	<ns3:fv_language>en-US</ns3:fv_language>
	<ns3:fv_nmtoken>nospace</ns3:fv_nmtoken>
	<ns3:fv_nmtokens>nospace1 nospace2</ns3:fv_nmtokens>
	<ns3:fv_integer>-6</ns3:fv_integer>
	<ns3:fv_nonPositiveInteger>0</ns3:fv_nonPositiveInteger>
	<ns3:fv_negativeInteger>-16</ns3:fv_negativeInteger>
	<ns3:fv_long>-7</ns3:fv_long>
	<ns3:fv_int>-5</ns3:fv_int>
	<ns3:fv_short>-8</ns3:fv_short>
	<ns3:fv_byte>-1</ns3:fv_byte>
	<ns3:fv_nonNegativeInteger>0</ns3:fv_nonNegativeInteger>
	<ns3:fv_unsignedLong>7</ns3:fv_unsignedLong>
	<ns3:fv_unsignedInt>5</ns3:fv_unsignedInt>
	<ns3:fv_unsignedShort>8</ns3:fv_unsignedShort>
	<ns3:fv_unsignedByte>1</ns3:fv_unsignedByte>
	<ns3:fv_positiveInteger>+16</ns3:fv_positiveInteger>
	
</ns3:document3>

=== gpitteloud/hisrc-basicjaxb/higher/tests/fixed-value/src/test/samples/document4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
List datatypes
	decimal  BigDecimal
	integer  BigInteger
	boolean  Boolean
	byte     Byte
	double   Double
	duration Duration
	float    Float
	int      Integer
	long     Long
	short    Short
	string   String
	dateTime XMLGregorianCalendar
-->
<ns4:document4
	xmlns:ns4="http://example.org/document" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://example.org/document ../../main/resources/document.xsd "
	
	fa_decimalValues="-7.50 5.75"
	fa_integerValues="-11 13"
	fa_booleanValues="true false"
	fa_byteValues="-128 127"
	fa_doubleValues="-3.14 2.718 -INF INF NaN"
	fa_durationValues="P3Y2M1D P6Y4M2D"
	fa_floatValues="-3.14 2.718 -INF INF NaN"
	fa_intValues="-123 123"
	fa_longValues="-123 123"
	fa_shortValues="-123 123"
	fa_dateTimeValues="2023-02-28T17:59:59.999Z 2023-03-01T17:59:59.999Z"
>
	<ns4:fv_decimalValues>-7.50 5.75</ns4:fv_decimalValues>
	<ns4:fv_integerValues>-11 13</ns4:fv_integerValues>
	<ns4:fv_booleanValues>true false</ns4:fv_booleanValues>
	<ns4:fv_byteValues>-128 127</ns4:fv_byteValues>
	<ns4:fv_doubleValues>-3.14 2.718 -INF INF NaN</ns4:fv_doubleValues>
	<ns4:fv_durationValues>P3Y2M1D P6Y4M2D</ns4:fv_durationValues>
	<ns4:fv_floatValues>-3.14 2.718 -INF INF NaN</ns4:fv_floatValues>
	<ns4:fv_intValues>-123 123</ns4:fv_intValues>
	<ns4:fv_longValues>-123 123</ns4:fv_longValues>
	<ns4:fv_shortValues>-123 123</ns4:fv_shortValues>
	<ns4:fv_stringValues>string1 string2</ns4:fv_stringValues>
	<ns4:fv_dateTimeValues>2023-02-28T17:59:59.999Z 2023-03-01T17:59:59.999Z</ns4:fv_dateTimeValues>	
</ns4:document4>

=== gpitteloud/hisrc-basicjaxb/higher/tests/fixed-value/src/test/samples/document1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:document1
	xmlns:ns1="http://example.org/document" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://example.org/document ../../main/resources/document.xsd "
	
	fa_limit="1000" 
	fa_dow="Monday" 
	fa_boolean="true" 
	fa_byte="1" 
	fa_decimal="2.1" 
	fa_double="3.1" 
	fa_float="4.1" 
	fa_int="5" 
	fa_integer="6" 
	fa_long="7" 
	fa_short="8" 
	fa_string="text" 
	fa_dateTime="2023-02-28T17:59:59.999Z" 
	fa_duration="P3Y2M1D" 
	fa_base64Binary="dGV4dA==" 
	fa_hexBinary="0FB8" 
	fa_anySimpleType="3.14159" 
>
	<ns1:fv_limit>1000</ns1:fv_limit>
	<ns1:fv_dow>Monday</ns1:fv_dow>
	<ns1:fv_boolean>true</ns1:fv_boolean>
	<ns1:fv_byte>-1</ns1:fv_byte>
	<ns1:fv_choice>
		<ns1:fv_boolean>true</ns1:fv_boolean>
	</ns1:fv_choice>
	<ns1:fv_decimal>-2.1</ns1:fv_decimal>
	<ns1:fv_double>-3.1</ns1:fv_double>
	<ns1:fv_float>-4.1</ns1:fv_float>
	<ns1:fv_int>-5</ns1:fv_int>
	<ns1:fv_integer>-6</ns1:fv_integer>
	<ns1:fv_long>-7</ns1:fv_long>
	<ns1:fv_short>-8</ns1:fv_short>
	<ns1:fv_string>text</ns1:fv_string>
	<ns1:fv_dateTime>2023-02-28T17:59:59.999Z</ns1:fv_dateTime>
	<ns1:fv_duration>P3Y2M1D</ns1:fv_duration>
	<ns1:fv_base64Binary>dGV4dA==</ns1:fv_base64Binary>
	<ns1:fv_hexBinary>0FB8</ns1:fv_hexBinary>
	<ns1:fv_anySimpleType>3.14159</ns1:fv_anySimpleType>
</ns1:document1>

=== gpitteloud/hisrc-basicjaxb/higher/tests/fixed-value/src/test/samples/document2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
3.2 Primitive datatypes
	3.2.1 string
	3.2.2 boolean
	3.2.3 decimal
	3.2.4 float
	3.2.5 double
	3.2.6 duration
	3.2.7 dateTime
	3.2.8 time
	3.2.9 date
	3.2.10 gYearMonth
	3.2.11 gYear
	3.2.12 gMonthDay
	3.2.13 gDay
	3.2.14 gMonth
	3.2.15 hexBinary
	3.2.16 base64Binary
	3.2.17 anyURI
	3.2.18 QName
	3.2.19 NOTATION
-->
<ns2:document2
	xmlns:ns2="http://example.org/document" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://example.org/document ../../main/resources/document.xsd "

	fa_string="text" 
	fa_boolean="true" 
	fa_decimal="2.1" 
	fa_float="4.1" 
	fa_double="3.1" 
	fa_duration="P3Y2M1D" 
	fa_dateTime="2023-02-28T17:59:59.999Z" 
	fa_time="23:59:59"
	fa_date="2023-02-28Z"
	fa_gYearMonth="2023-02Z"
	fa_gYear="2023Z"
	fa_gMonthDay="--02-28Z"
	fa_gDay="---28Z"
	fa_gMonth="--02Z"
	fa_hexBinary="0FB8" 
	fa_base64Binary="dGV4dA==" 
	fa_anyURI="scheme://authority/path?query#fragment"
	fa_QName="ns2:localPart"
>
	<ns2:fv_string>text</ns2:fv_string>
	<ns2:fv_boolean>true</ns2:fv_boolean>
	<ns2:fv_decimal>-2.1</ns2:fv_decimal>
	<ns2:fv_float>-4.1</ns2:fv_float>
	<ns2:fv_double>-3.1</ns2:fv_double>
	<ns2:fv_duration>P3Y2M1D</ns2:fv_duration>
	<ns2:fv_dateTime>2023-02-28T17:59:59.999Z</ns2:fv_dateTime>
	<ns2:fv_time>23:59:59</ns2:fv_time>
	<ns2:fv_date>2023-02-28Z</ns2:fv_date>
	<ns2:fv_gYearMonth>2023-02Z</ns2:fv_gYearMonth>
	<ns2:fv_gYear>2023Z</ns2:fv_gYear>
	<ns2:fv_gMonthDay>--02-28Z</ns2:fv_gMonthDay>
	<ns2:fv_gDay>---28Z</ns2:fv_gDay>
	<ns2:fv_gMonth>--02Z</ns2:fv_gMonth>
	<ns2:fv_hexBinary>0FB8</ns2:fv_hexBinary>
	<ns2:fv_base64Binary>dGV4dA==</ns2:fv_base64Binary>
	<ns2:fv_anyURI>scheme://authority/path?query#fragment</ns2:fv_anyURI>
	<ns2:fv_QName>ns2:localPart</ns2:fv_QName>
</ns2:document2>
